#default: &default
#  adapter: postgresql
#  encoding: unicode
#  host: localhost
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling

default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost

development:
  <<: *default
  database: sloc_development
  username: root
  password: root

test:
  <<: *default
  database: sloc_test
  username: root
  password: root

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: sloc_production
  username: sloc
  password: root
